### ISSUE TITLE
Hard max cache size exceeded

### ISSUE THREAD

**Issue by Freeaqingme** [allegro/bigcache#18] opened 2016-05-23 10:40 UTC
Howdy,

Last week I was able to deploy my new version of [ClueGetter](https://github.com/Freeaqingme/ClueGetter) to production. This morning Icinga alerted that pretty much everywhere where I had deployed last week we were running out of ram. A profile of the heap shows: http://storage8.static.itmages.com/i/16/0523/h_1463999604_2310069_9f039a5d50.png

How it's initialized can be seen here: https://github.com/Freeaqingme/ClueGetter/blob/develop/src/cluegetter/messagePersist.go#L431 . Most notably the: 'HardMaxCacheSize: 1024'.

I realize I'm actually instantiating two caches. Even though msgIdIdx should only contain a few MB max. However, 2x1024 MB would be ~2 GiB. Not the 2977.6+444.59 MBthat the heap profile shows?

**Comment by janisz** [comment] 2016-05-23 12:08
Hi @Freeaqingme 

Thanks for submitting issue. At the first glance it looks weird. `bigcache` keeps one big array where all entries are stored. But we doesn't monitor size of internal map containing offset. Another thing that could make application eating so much memory is GC not freeing it — could you post your GC settings and GC log.

I hope I can create [Minimal, Complete, and Verifiable example](http://stackoverflow.com/help/mcve) and debug this problem. If you already have it please share.

**Comment by janisz** [comment] 2016-06-07 08:33
I'm sorry for the delay. I think I was able to reproduce issue with [this code](https://gist.github.com/janisz/d04301463dd663584a2498f4ec086c1c)

**Comment by Freeaqingme** [comment] 2016-06-07 15:58
I'm sorry for the delay as well. It's still on my list, but had some more urgent things coming up first. Having said that, if you're able to reproduce it then at least we have got the first step towards fixing it :)

**Comment by druminski** [comment] 2016-06-15 16:25
Hi,

This issue is directly related with `map` implementation in go. I created a [ticket](https://github.com/golang/go/issues/16070) for it on a go lang issue tracker. I don't know when it will be fixed, but I will try to take a look on map implementation in a free time, maybe I will be able to propose some solution.

**Comment by druminski** [comment] 2016-09-06 19:55
I am closing the issue as there is nothing to do in bigcache to solve it. There was presented a fix for golang map in a ticket which I created. It will be probably released in go version 1.8

**Closed by druminski** 2016-09-06 19:55 UTC
Labels: bug

**Comment by janisz** [comment] 2016-09-13 18:20
Looks like[ golang #1670](https://github.com/golang/go/issues/16070#issuecomment-233764084) was solved!
