### ISSUE TITLE
Memory usage grows indefinitely

### ISSUE THREAD

**Issue by tangtony** [allegro/bigcache#109] opened 2018-12-06 23:15 UTC
Hello,

I've been playing around with bigcache and I've noticed that calling Set() with the same keys causes the memory usage to grow indefinitely. Here's an example:

```go
cache, _ := bigcache.NewBigCache(bigcache.DefaultConfig(10 * time.Minute))
data := []byte("TESTDATATESTDATATESTDATATESTDATATESTDATATESTDATATESTDATA")

for {
	for i := 0; i < 10000; i++ {
		cache.Set(strconv.Itoa(i), data)
	}
	time.Sleep(time.Second)
}
```

Running that causes the memory usage of the application to grow indefinitely until I ran out of memory.. Is this expected behaviour? I'm just using bigcache as if it was a concurrent map and I would have expected the elements to get replaced and thus memory usage shouldn't grow beyond what is necessary for 10,000 elements.

**Comment by mxplusb** [comment] 2019-02-14 20:54
@tangtony I've been arbitrarily working on a test use case on this, I'll let you know what I come up with.

**Comment by AntSeoTeam** [comment] 2019-03-10 14:31
hello
Has the problem been solved？

**Comment by FarhadF** [comment] 2019-05-27 09:28
We got the same issue here

**Comment by mdogan** [comment] 2019-06-14 16:13
Isn't this because with `DefaultConfig()` `CleanWindow` is `0`, so expired entries are not removed from cache? 

```go
// Interval between removing expired entries (clean up).
// If set to <= 0 then no action is performed. Setting to < 1 second is counterproductive — bigcache has a one second resolution.
CleanWindow time.Duration

// DefaultConfig initializes config with default values.
// When load for BigCache can be predicted in advance then it is better to use custom config.
func DefaultConfig(eviction time.Duration) Config {
	return Config{
		Shards:             1024,
		LifeWindow:         eviction,
		CleanWindow:        0,
...
```

Afaik `bigcache` can store multiple versions of the same key in the buffer.

**Comment by mingard** [comment] 2019-08-16 12:52
Even with the following config I'm still seeing exponential growth in memory usage:

```go
bigcache.Config{
  LifeWindow:   30 * time.Second,
  CleanWindow:  1 * time.Second,
}
```

They appear to be removed from `cacheShard.hashmap`, but cleanup aren't followed by a reduction in memory usage.

OS: Ubuntu 18.04.2 LTS

**Comment by mxplusb** [comment] 2019-08-16 18:16
@cristaloleg or @janisz is this unexpected behaviour? Because we don't use pointers, there's no garbage collection runs against allocated objects, so no memory would ever be freed.

https://github.com/allegro/bigcache#how-it-works

**Comment by cristaloleg** [comment] 2019-08-16 19:05
I'm curios what will happen if @mingard will invoke https://godoc.org/runtime#GC once per minute.

That's a really strange behaviour that Bigcache still allocates memory.

**Comment by mingard** [comment] 2019-08-23 11:58
@cristaloleg We've done a lot of investigation and it looks like even with GC calls, the system isn't freeing up memory. 

We ended up looking at the way bigcache handles eviction, and it appears that it's a little lazy (in a good way). Whilst memory is marked as free, it doesn't perform eviction until a new item inserted.

This was confirmed by digging through similar issues to find this comment: https://github.com/allegro/bigcache/issues/31#issuecomment-280340592

It looks like this is covered in a blog post somewhere, but it feels like something that is worthy of the README.

**Comment by cristaloleg** [comment] 2019-08-23 12:02
Thanks for the information, looks like you've observing this behaviour: https://utcc.utoronto.ca/~cks/space/blog/programming/GoNoMemoryFreeing

Yep, mentioning such behaviour in README is a good idea, do you want to try? 😉

**Comment by mingard** [comment] 2019-08-23 12:40
@cristaloleg https://github.com/allegro/bigcache/pull/154

**Comment by cristaloleg** [comment] 2019-08-26 07:12
Fixed in https://github.com/allegro/bigcache/pull/154

**Closed by cristaloleg** 2019-08-26 07:12 UTC
Labels: discussion

**Comment by FarhadF** [comment] 2019-08-26 12:47
I think this is not the behavior. You can disable it on go 1.12 with GODEBUG=madvdontneed=1 flag or use go 1.10 and still go OOM while doing OP test. I worked around it by limiting overall bigcache memory with ```HardMaxCacheSize``` but it is not ideal as it reduces performance
