### ISSUE TITLE
benchmarks gives error

### ISSUE THREAD

**Issue by andersfylling** [allegro/bigcache#100] opened 2018-10-21 18:26 UTC
```go
caches_bench git:(master) go test -bench=. -benchtime=10s ./... -timeout 30m 
goos: linux
goarch: amd64
pkg: github.com/allegro/bigcache/caches_bench
BenchmarkMapSet-8                     	50000000	       477 ns/op
BenchmarkConcurrentMapSet-8           	10000000	      1066 ns/op
BenchmarkFreeCacheSet-8               	30000000	       746 ns/op
BenchmarkBigCacheSet-8                	30000000	       449 ns/op
BenchmarkMapGet-8                     	50000000	       275 ns/op
BenchmarkConcurrentMapGet-8           	50000000	       344 ns/op
BenchmarkFreeCacheGet-8               	30000000	       642 ns/op
BenchmarkBigCacheGet-8                	30000000	       420 ns/op
BenchmarkBigCacheSetParallel-8        	fatal error: runtime: out of memory

runtime stack:
runtime.throw(0x549559, 0x16)
	/usr/lib/go/src/runtime/panic.go:608 +0x72
runtime.sysMap(0xc704000000, 0x4000000, 0x65a5f8)
	/usr/lib/go/src/runtime/mem_linux.go:156 +0xc7
runtime.(*mheap).sysAlloc(0x640820, 0x4000000, 0x640838, 0x7fd4969a8ac0)
	/usr/lib/go/src/runtime/malloc.go:619 +0x1c7
runtime.(*mheap).grow(0x640820, 0x1, 0x0)
	/usr/lib/go/src/runtime/mheap.go:920 +0x42
runtime.(*mheap).allocSpanLocked(0x640820, 0x1, 0x65a608, 0x400)
	/usr/lib/go/src/runtime/mheap.go:848 +0x337
runtime.(*mheap).alloc_m(0x640820, 0x1, 0x7, 0x7fd46baadfff)
	/usr/lib/go/src/runtime/mheap.go:692 +0x119
runtime.(*mheap).alloc.func1()
	/usr/lib/go/src/runtime/mheap.go:759 +0x4c
runtime.(*mheap).alloc(0x640820, 0x1, 0x7fd46b010007, 0x7fd4969a8b58)
	/usr/lib/go/src/runtime/mheap.go:758 +0x8a
runtime.(*mcentral).grow(0x641d18, 0x0)
	/usr/lib/go/src/runtime/mcentral.go:232 +0x94
runtime.(*mcentral).cacheSpan(0x641d18, 0x1969a8b58)
	/usr/lib/go/src/runtime/mcentral.go:106 +0x2f8
runtime.(*mcache).refill(0x7fd4c2b10d80, 0x45a707)
	/usr/lib/go/src/runtime/mcache.go:122 +0x95
runtime.(*mcache).nextFree.func1()
	/usr/lib/go/src/runtime/malloc.go:749 +0x32
runtime.systemstack(0x0)
	/usr/lib/go/src/runtime/asm_amd64.s:351 +0x66
runtime.mstart()
	/usr/lib/go/src/runtime/proc.go:1229

goroutine 147 [running]:
runtime.systemstack_switch()
	/usr/lib/go/src/runtime/asm_amd64.s:311 fp=0xc011a74cd8 sp=0xc011a74cd0 pc=0x456d60
runtime.(*mcache).nextFree(0x7fd4c2b10d80, 0x7, 0x2, 0x1, 0xc)
	/usr/lib/go/src/runtime/malloc.go:748 +0xb6 fp=0xc011a74d30 sp=0xc011a74cd8 pc=0x40b036
runtime.mallocgc(0x20, 0x0, 0x0, 0x0)
	/usr/lib/go/src/runtime/malloc.go:903 +0x793 fp=0xc011a74dd0 sp=0xc011a74d30 pc=0x40b983
runtime.slicebytetostring(0x0, 0xc000012160, 0x11, 0x20, 0x0, 0x0)
	/usr/lib/go/src/runtime/string.go:102 +0x9f fp=0xc011a74e00 sp=0xc011a74dd0 pc=0x443fcf
fmt.Sprintf(0x5475ee, 0xd, 0xc011a74e90, 0x2, 0x2, 0x5dd2972212259774, 0xc011a74f14)
	/usr/lib/go/src/fmt/print.go:204 +0x92 fp=0xc011a74e58 sp=0xc011a74e00 pc=0x49ab52
github.com/allegro/bigcache/caches_bench.parallelKey(0x22c, 0x98b595, 0x11, 0xc011a74f14)
	/home/anders/go/src/github.com/allegro/bigcache/caches_bench/caches_bench_test.go:206 +0xbf fp=0xc011a74ec0 sp=0xc011a74e58 pc=0x4f9d8f
github.com/allegro/bigcache/caches_bench.BenchmarkBigCacheSetParallel.func1(0xc0a76d6000)
	/home/anders/go/src/github.com/allegro/bigcache/caches_bench/caches_bench_test.go:111 +0x74 fp=0xc011a74f90 sp=0xc011a74ec0 pc=0x4f9ee4
testing.(*B).RunParallel.func1(0xc0000145c0, 0xc0000145b8, 0xc0000145b0, 0xc000094000, 0xc0000541d0)
	/usr/lib/go/src/testing/benchmark.go:626 +0x97 fp=0xc011a74fb8 sp=0xc011a74f90 pc=0x4b7977
runtime.goexit()
	/usr/lib/go/src/runtime/asm_amd64.s:1333 +0x1 fp=0xc011a74fc0 sp=0xc011a74fb8 pc=0x458cc1
created by testing.(*B).RunParallel
	/usr/lib/go/src/testing/benchmark.go:619 +0x192

goroutine 1 [chan receive, 1 minutes]:
testing.(*B).doBench(0xc000094000, 0x0, 0x0, 0x0, 0x0, 0x0)
	/usr/lib/go/src/testing/benchmark.go:260 +0x77
testing.(*benchContext).processBench(0xc00000a0c0, 0xc000094000)
	/usr/lib/go/src/testing/benchmark.go:447 +0x2ec
testing.(*B).run(0xc000094000)
	/usr/lib/go/src/testing/benchmark.go:251 +0x74
testing.(*B).Run(0xc000094340, 0x54a7a3, 0x1c, 0x54f0e8, 0x4adf00)
	/usr/lib/go/src/testing/benchmark.go:515 +0x2e1
testing.runBenchmarks.func1(0xc000094340)
	/usr/lib/go/src/testing/benchmark.go:416 +0x78
testing.(*B).runN(0xc000094340, 0x1)
	/usr/lib/go/src/testing/benchmark.go:141 +0xb2
testing.runBenchmarks(0x54d07d, 0x28, 0xc00000a0a0, 0x6388c0, 0xe, 0xe, 0x80)
	/usr/lib/go/src/testing/benchmark.go:422 +0x323
testing.(*M).Run(0xc0000ac000, 0x0)
	/usr/lib/go/src/testing/testing.go:1040 +0x37c
main.main()
	_testmain.go:68 +0x13d

goroutine 15 [semacquire]:
sync.runtime_Semacquire(0xc0000145c8)
	/usr/lib/go/src/runtime/sema.go:56 +0x39
sync.(*WaitGroup).Wait(0xc0000145c0)
	/usr/lib/go/src/sync/waitgroup.go:130 +0x64
testing.(*B).RunParallel(0xc000094000, 0xc0000541d0)
	/usr/lib/go/src/testing/benchmark.go:629 +0x1b2
github.com/allegro/bigcache/caches_bench.BenchmarkBigCacheSetParallel(0xc000094000)
	/home/anders/go/src/github.com/allegro/bigcache/caches_bench/caches_bench_test.go:107 +0xc3
testing.(*B).runN(0xc000094000, 0x5f5e100)
	/usr/lib/go/src/testing/benchmark.go:141 +0xb2
testing.(*B).launch(0xc000094000)
	/usr/lib/go/src/testing/benchmark.go:290 +0xbf
created by testing.(*B).doBench
	/usr/lib/go/src/testing/benchmark.go:259 +0x59

goroutine 146 [runnable]:
fmt.(*pp).free(0xc0a76d4000)
	/usr/lib/go/src/fmt/print.go:141 +0xb4
fmt.Sprintf(0x5475ee, 0xd, 0xc011a5ce90, 0x2, 0x2, 0x4fb212810910e3e3, 0xc011a5cf14)
	/usr/lib/go/src/fmt/print.go:205 +0xb4
github.com/allegro/bigcache/caches_bench.parallelKey(0x7, 0x94e699, 0x10, 0xc011a5cf14)
	/home/anders/go/src/github.com/allegro/bigcache/caches_bench/caches_bench_test.go:206 +0xbf
github.com/allegro/bigcache/caches_bench.BenchmarkBigCacheSetParallel.func1(0xc0a76d2000)
	/home/anders/go/src/github.com/allegro/bigcache/caches_bench/caches_bench_test.go:111 +0x74
testing.(*B).RunParallel.func1(0xc0000145c0, 0xc0000145b8, 0xc0000145b0, 0xc000094000, 0xc0000541d0)
	/usr/lib/go/src/testing/benchmark.go:626 +0x97
created by testing.(*B).RunParallel
	/usr/lib/go/src/testing/benchmark.go:619 +0x192

goroutine 145 [running]:
	goroutine running on other thread; stack unavailable
created by testing.(*B).RunParallel
	/usr/lib/go/src/testing/benchmark.go:619 +0x192

goroutine 148 [running]:
	goroutine running on other thread; stack unavailable
created by testing.(*B).RunParallel
	/usr/lib/go/src/testing/benchmark.go:619 +0x192

goroutine 149 [running]:
	goroutine running on other thread; stack unavailable
created by testing.(*B).RunParallel
	/usr/lib/go/src/testing/benchmark.go:619 +0x192

goroutine 150 [running]:
	goroutine running on other thread; stack unavailable
created by testing.(*B).RunParallel
	/usr/lib/go/src/testing/benchmark.go:619 +0x192

goroutine 151 [running]:
	goroutine running on other thread; stack unavailable
created by testing.(*B).RunParallel
	/usr/lib/go/src/testing/benchmark.go:619 +0x192

goroutine 152 [running]:
	goroutine running on other thread; stack unavailable
created by testing.(*B).RunParallel
	/usr/lib/go/src/testing/benchmark.go:619 +0x192
exit status 2
FAIL	github.com/allegro/bigcache/caches_bench	375.990s
```

go env:
```go
GOARCH="amd64"
GOBIN=""
GOCACHE="/home/anders/.cache/go-build"
GOEXE=""
GOFLAGS=""
GOHOSTARCH="amd64"
GOHOSTOS="linux"
GOOS="linux"
GOPATH="/home/anders/go"
GOPROXY=""
GORACE=""
GOROOT="/usr/lib/go"
GOTMPDIR=""
GOTOOLDIR="/usr/lib/go/pkg/tool/linux_amd64"
GCCGO="gccgo"
CC="gcc"
CXX="g++"
CGO_ENABLED="1"
GOMOD=""
CGO_CFLAGS="-g -O2"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-g -O2"
CGO_FFLAGS="-g -O2"
CGO_LDFLAGS="-g -O2"
PKG_CONFIG="pkg-config"
GOGCCFLAGS="-fPIC -m64 -pthread -fmessage-length=0 -fdebug-prefix-map=/tmp/go-build910620148=/tmp/go-build -gno-record-gcc-switches"
```

**Comment by cristaloleg** [comment] 2018-10-21 18:27
How much ram do you have?

**Comment by andersfylling** [comment] 2018-10-21 18:44
32GiB

**Comment by cristaloleg** [comment] 2018-10-22 13:21
Well, I cannot reproduce this failure. 
Let me guess, 0Mb swap? :)

**Comment by andersfylling** [comment] 2018-10-22 18:42
Nope. 4GB swap.

**Comment by andersfylling** [comment] 2018-10-26 22:33
Which version of go are you running?

**Comment by mxplusb** [comment] 2019-02-14 20:51
I also was not able to reproduce this, on Windows or Ubuntu.

```powershell
PS P:\go\src\github.com\allegro\bigcache\caches_bench> go test -bench . -benchtime 1s ./... -timeout 30m
goos: windows
goarch: amd64
pkg: github.com/allegro/bigcache/caches_bench
BenchmarkMapSet-8                        5000000               466 ns/op
BenchmarkConcurrentMapSet-8              1000000              1479 ns/op
BenchmarkFreeCacheSet-8                  3000000               530 ns/op
BenchmarkBigCacheSet-8                   3000000               465 ns/op
BenchmarkMapGet-8                        5000000               356 ns/op
BenchmarkConcurrentMapGet-8              5000000               387 ns/op
BenchmarkFreeCacheGet-8                  3000000               654 ns/op
BenchmarkBigCacheGet-8                   3000000               435 ns/op
BenchmarkBigCacheSetParallel-8          10000000               192 ns/op
BenchmarkFreeCacheSetParallel-8         10000000               195 ns/op
BenchmarkConcurrentMapSetParallel-8      5000000               305 ns/op
BenchmarkBigCacheGetParallel-8          20000000               108 ns/op
BenchmarkFreeCacheGetParallel-8         20000000               117 ns/op
BenchmarkConcurrentMapGetParallel-8     10000000               213 ns/op
PASS
ok      github.com/allegro/bigcache/caches_bench        92.819s
PS P:\go\src\github.com\allegro\bigcache\caches_bench> git rev-parse HEAD
84a0ff3f153cbd7e280a19029a864bb04b504e62
PS P:\go\src\github.com\allegro\bigcache\caches_bench> go version
go version go1.11.2 windows/amd64
```

```bash
mike@boulder /p/go/src/github.com/allegro/bigcache/caches_bench
 %  go test -bench . -benchtime 1s ./... -timeout 30m
goos: linux
goarch: amd64
pkg: github.com/allegro/bigcache/caches_bench
BenchmarkMapSet-8                        3000000               439 ns/op
BenchmarkConcurrentMapSet-8              1000000              1481 ns/op
BenchmarkFreeCacheSet-8                   500000              2588 ns/op
BenchmarkBigCacheSet-8                    500000              2632 ns/op
BenchmarkMapGet-8                        5000000               339 ns/op
BenchmarkConcurrentMapGet-8              5000000               371 ns/op
BenchmarkFreeCacheGet-8                   500000              2699 ns/op
BenchmarkBigCacheGet-8                   3000000               442 ns/op
BenchmarkBigCacheSetParallel-8           2000000               647 ns/op
BenchmarkFreeCacheSetParallel-8          2000000               741 ns/op
BenchmarkConcurrentMapSetParallel-8      5000000               313 ns/op
BenchmarkBigCacheGetParallel-8          20000000               201 ns/op
BenchmarkFreeCacheGetParallel-8          2000000               722 ns/op
BenchmarkConcurrentMapGetParallel-8     10000000               184 ns/op
PASS
ok      github.com/allegro/bigcache/caches_bench        142.104s
mike@boulder /p/go/src/github.com/allegro/bigcache/caches_bench
 % git rev-parse HEAD
84a0ff3f153cbd7e280a19029a864bb04b504e62
mike@boulder /p/go/src/github.com/allegro/bigcache/caches_bench
 % go version
go version go1.11.2 linux/amd64
```

Closing for now, please let us know if you are still stuck.

**Closed by mxplusb** 2019-02-14 20:51 UTC
